### ISSUE TITLE
Trying to deploy sample java app facing issue while deploying the service

### ISSUE THREAD

**Issue by Santosh-Kumar-Perumal** [GoogleCloudPlatform/opentelemetry-operator-sample#75]
Command that is failing - **kubectl apply -f k8s/.**
https://github.com/GoogleCloudPlatform/opentelemetry-operator-sample/blob/main/sample-apps/java/README.md

Error
2024-02-15 22:29:00.044 GMT
Error: LinkageError occurred while loading main class com.google.example.service.Main
2024-02-15 22:29:00.044 GMT
	java.lang.UnsupportedClassVersionError: com/google/example/service/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

I am building and running my application in Google cloud shell.
$ java -version
openjdk version "17.0.10" 2024-01-16
OpenJDK Runtime Environment (build 17.0.10+7-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.10+7-Debian-1deb11u1, mixed mode, sharing)

**Comment by damemi** [comment]
@psx95 or @aabmass are you more familiar with the Java build steps to debug this? Looks like it's something with the sample app image that users build in [`make build`](https://github.com/GoogleCloudPlatform/opentelemetry-operator-sample/blob/e89e35c6ecca3c042ebd049d6e5e9eb25fd46c3a/sample-apps/java/Makefile#L18)

**Comment by Santosh-Kumar-Perumal** [comment]
Please help with the fix looks like something to do with the java version.

**Comment by psx95** [comment]
I'll take a look into this.

**Comment by psx95** [comment]
I retried the steps from [Readme](https://github.com/GoogleCloudPlatform/opentelemetry-operator-sample/blob/main/sample-apps/java/README.md#java-sample-app), but was not able to reproduce the problem. 

```
kubectl apply -f k8s/.

// results in the following
cronjob.batch/javashowcase-app created
service/javashowcase-service created
deployment.apps/javashowcase-service created
```

The logs from the docker container also do not show the version mismatch error.

Where exactly do you see this message ?  Since the service runs in a docker container, version mismatch should not occur.

**Comment by Santosh-Kumar-Perumal** [comment]
Steps that I am following.

- Created a standard GKE Kubernetes cluster. 
- Connected to the GKE Cluster from google cloud shell.
- Installed Open Telemetry Operator and started the collector with these steps. [Readme](https://github.com/GoogleCloudPlatform/opentelemetry-operator-sample/blob/main/README.md)
- While following thorough these steps got issue at step two  **kubectl apply -f k8s/.** this command was executed in Google cloud shell.

**Comment by psx95** [comment]
Thank you for providing the additional information. I will take a closer look into this, following the steps you have mentioned.

**Comment by Santosh-Kumar-Perumal** [comment]
Some of my suspects for the issue as per my build log as attached in the last comment.

https://github.com/runningcode/gradle-doctor/pull/195/files#diff-c0dfa6bc7a8685217f70a860145fbdf416d449eaff052fa28352c5cec1a98c06R28

https://github.com/GoogleCloudPlatform/opentelemetry-operator-sample/blob/main/sample-apps/java/gradle/wrapper/gradle-wrapper.properties#L3

**Comment by Santosh-Kumar-Perumal** [comment]
I tried building go sample app it is coming up without any issue the problem is when I build the java app.

 => => naming to us-central1-docker.pkg.dev/tribal-joy-413413/otel-operator/go-sample-server                                                                                         0.0s
aperumal_personalid@cloudshell:~/opentelemetry-operator-sample/**sample-apps/go** (tribal-joy-413413)$ kubectl apply -f k8s/.
deployment.apps/goshowcase-app created
service/goshowcase-server created
deployment.apps/goshowcase-server created
aperumal_personalid@cloudshell:~/opentelemetry-operator-sample/sample-apps/go (tribal-joy-413413)$

**Comment by psx95** [comment]
Hi @Santosh-Kumar-Perumal,
Thank you digging into this issue ! I was able to reproduce this issue on cloud shell through your steps. The sample does need some changes to fix this.

### Background & Root Cause
We use jib to build & run the Java sample - based on the "[What is jib?](https://github.com/GoogleContainerTools/jib/tree/master?tab=readme-ov-file#what-is-jib)" - it seems like jib builds the applications without the Docker daemon - which means it is using the Java version that is locally installed on your machine to compile the code into `.class` files.

On Cloud Shell, this appears to be Java 17. However, jib runs the compiled code in a docker container for which the base image is Java 11. This configuration is specified [here](https://github.com/GoogleCloudPlatform/opentelemetry-operator-sample/blob/e89e35c6ecca3c042ebd049d6e5e9eb25fd46c3a/sample-apps/java/buildSrc/src/main/kotlin/com.google.example.java-application-conventions.gradle.kts#L12), which leads to a version mismatch error.

### Fix
In order to fix this, source and target compatibility need to be explicitly defined in [this build.gradle.kts file](https://github.com/GoogleCloudPlatform/opentelemetry-operator-sample/blob/main/sample-apps/java/buildSrc/src/main/kotlin/com.google.example.java-common-conventions.gradle.kts): 

```kotlin
java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}
```

This would tell gradle to build the source files explicitly for Java 11.

I did a small experiment and this does seem to work, I will raise a PR to make this change and confirm, but in the mean time,  you could try this on your end too.

#### Other notes
 - Thank you for bringing the slow build issue to light, I will see if I can update the gradle version we use as well.

**Comment by Santosh-Kumar-Perumal** [comment]
Thanks for the quick fix appreciate it @psx95 
I was able to build the service successfully now I am trying to access the service once it is deployed but facing below issue.Can you check at your end if you can access the service ?

![image](https://github.com/GoogleCloudPlatform/opentelemetry-operator-sample/assets/16875250/ba3f50f1-c86e-4bb5-9354-a11af2dcb700)
![image](https://github.com/GoogleCloudPlatform/opentelemetry-operator-sample/assets/16875250/531e91d8-210f-4bf7-af58-b4f3f534c0f7)

**Comment by Santosh-Kumar-Perumal** [comment]
Thanks a lot I was using the collector-config.yaml that is outside after using the one that is present inside cloud-trace I am able to see the trace coming up.

"Big shoutout to @Google and team members @psx95  and @damemi  for their lightning-fast response and invaluable assistance in resolving my GitHub ticket. Their guidance and support throughout the process were instrumental. Thank you for your dedication and expertise! 🙌 #TechSupport #GitHubHeroes"

🌟 Major kudos for your brilliance and dedication! 🙌 #TechGeniuses #GitHubHeroes"
